language: node_js

node_js:
  - '12'

install:
  - npm ci

script:
  - npm run init
  - npm run build
  - npm test
  - npm run cypress:ci
  - npm run lint
  - npx lerna run ci:test
  - npx lerna run ci:build
